const productos = [
    {
        id: 1,
        nombre: "Laptop Gaming MSI",
        precio: 1299,
        precioOriginal: null,
        categoria: "Portátiles",
        stock: 8,
        enOferta: false,
    },
    {
        id: 2,
        nombre: "iPhone 15 Pro",
        precio: 999,
        precioOriginal: 1199,
        categoria: "Smartphones",
        stock: 15,
        enOferta: true,
    },
    {
        id: 3,
        nombre: "Mouse Logitech MX Master",
        precio: 89,
        precioOriginal: null,
        categoria: "Accesorios",
        stock: 25,
        enOferta: false,
    },
    {
        id: 4,
        nombre: 'Monitor Samsung 32" 4K',
        precio: 449,
        precioOriginal: 599,
        categoria: "Monitores",
        stock: 12,
        enOferta: true,
    },
    {
        id: 5,
        nombre: "Teclado Mecánico Corsair",
        precio: 159,
        precioOriginal: null,
        categoria: "Accesorios",
        stock: 18,
        enOferta: false,
    },
    {
        id: 6,
        nombre: "AirPods Pro 2",
        precio: 199,
        precioOriginal: 249,
        categoria: "Audio",
        stock: 30,
        enOferta: true,
    },
    {
        id: 7,
        nombre: "PlayStation 5",
        precio: 549,
        precioOriginal: null,
        categoria: "Consolas",
        stock: 5,
        enOferta: false,
    },
    {
        id: 8,
        nombre: "Webcam Logitech 4K",
        precio: 129,
        precioOriginal: 179,
        categoria: "Accesorios",
        stock: 22,
        enOferta: true,
    },
];
